name: Reusable - Docker Push

on:
  workflow_call:
    inputs:
      image_name: { required: true, type: string }
      dockerfile_path: { required: false, type: string, default: "Dockerfile" }
      context: { required: false, type: string, default: "." }
    secrets:
      DOCKERHUB_USERNAME: { required: true }
      DOCKERHUB_TOKEN: { required: true }

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.image_name }} -f ${{ inputs.dockerfile_path }} ${{ inputs.context }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image
        run: |
          docker tag ${{ inputs.image_name }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:latest
