name: Reusable  - CI (Build + Trivy)

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      context:
        required: true
        type: string
  
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug - Show Inputs & Directory
        run: |
          echo "Service Name: ${{ inputs.service_name }}"
          echo "Dockerfile Path: ${{ inputs.dockerfile_path }}"
          echo "Context Path: ${{ inputs.context }}"
          ls -lR ${{ inputs.context }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ inputs.service_name }} \
            -f ${{ inputs.dockerfile_path }} \
            ${{ inputs.context }}
      - name: 🔎 Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.service_name }}
          format: table
          ignore-unfixed: true
          severity: CRITICAL,HIGH
      